import Head from "next/head";
import styles from "../styles/Home.module.css";
import React, { useState } from "react";
import { AudioPlayer } from "../Components/AudioPlayer";
import SongCards from "../Components/SongCards";

export default function Home() {
  // ! Router.query is a function that returns the query object

  // ! state
  const [isPlaying, setIsPlaying] = useState(false);
  const [duration, setDuration] = useState(0);
  const [currentTime, setCurrentTime] = useState(0);
  const [audio, setAudio] = useState(null);
  const [image, setImage] = useState(null);
  const [muted, setMuted] = useState(false);
  const [songTitle, setSongTitle] = useState("");
  const [songArtist, setSongArtist] = useState("");
  const [heartFill, setHeartFill] = useState(false);
  const [repeatSong, setRepeatSong] = useState(false);

  return (
    <div className={styles.container}>
      <Head>
        <title>React Audio Player</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <AudioPlayer
          isPlaying={isPlaying}
          duration={duration}
          currentTime={currentTime}
          audio={audio}
          image={image}
          muted={muted}
          heartFill={heartFill}
          repeatSong={repeatSong}
          songTitle={songTitle}
          songArtist={songArtist}
          setIsPlaying={setIsPlaying}
          setDuration={setDuration}
          setCurrentTime={setCurrentTime}
          setAudio={setAudio}
          setImage={setImage}
          setHeartFill={setHeartFill}
          setRepeatSong={setRepeatSong}
          setMuted={setMuted}
          setSongTitle={setSongTitle}
          setSongArtist={setSongArtist}
        />
        <SongCards
          audio={audio}
          image={image}
          songTitle={songTitle}
          songArtist={songArtist}
          setAudio={setAudio}
          setImage={setImage}
          setSongTitle={setSongTitle}
          setSongArtist={setSongArtist}
        />
      </main>
    </div>
  );
}
